version: "1.0"

volumes:
  certs:
  db:

services:
  ssl-certificate-generator:
    image: alpine/openssl:latest
    container_name: ssl-certificate-generator
    working_dir: /certs
    volumes:
      - certs:/certs
    # openssl command called automatically, only need to define the arguments
    command: req -x509 -nodes -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -subj '/CN=localhost'

  router:
    image: nginx:alpine
    container_name: router-dev
    volumes:
      - ./router/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certs:/certs:ro
    depends_on:
      backend:
        condition: service_started
      ssl-certificate-generator:
        condition: service_completed_successfully
    ports:
      - "80:80"
      - "443:443"
    environment:
      TZ: ${TZ}

  backend:
    container_name: backend-dev
    image: oven/bun
    working_dir: /backend
    command: bun --hot src/index.ts
    ports:
      - "${BE_PORT}:${BE_PORT}"
    environment:
      PORT: ${BE_PORT}
      HOST: ${BE_HOST}
      TZ: ${TZ}
    volumes:
      - ./backend:/backend
      - db:/database
    depends_on:
      database-prep:
        condition: service_completed_successfully

  database-prep:
    container_name: database-prep
    image: oven/bun
    working_dir: /database
    volumes:
      - ./database:/database
      - db:/generated
    command: bun index.ts
    environment:
      TZ: ${TZ}

